### PR TITLE
Rework.

### PR DESCRIPTION
**Pull request by ypid**
While working with ownCloud I had some debugging to do to figure out that when
trying to mount SMB/CIFS shares by ownCloud, it might be necessary to set the
correct workgroup in `/etc/samba/smb.conf` for this to work. So I polished this role a bit to make it do that.
Note that I did not address issue #2 with this because I don’t currently need the Samba daemon yet.

* Added support to only configure `/etc/samba/smb.conf` without installing the
  Samba daemon.
* Added Changelog.
* Converted `defaults/main.yml` to new documentation format and improved
  documentation.
* Put kernel modules loaded by this role to a separate file under
  `/etc/modules-load.d` managed by this role.
* Compared default configuration of the role and adjusted it to the default
  configuration distributed by Debian Jessie as of 4.2.10. Example: `map_to_guest`
* Updated metadata.
* Regenerated README.md.
* Use YAML tasks syntax.
* Use `ansible_managed`.
* Changed variable namespace from `samba_` to `samba__`.

### CODE REVIEW

**Comment by drybjed** [comment]
Thanks! I'm not sure what's happening with the travis test... I'll check that out a bit later.

**Comment by drybjed** [comment]
@ypid Test on Travis is now working, however it seems that the role does not support old `samba` packages in Ubuntu Precise, whuch had IIRC split services `smbd` and `nmbd`. Do you think this could be handled by the role (more complication), or should I try enabling Trusty packages in the test?

**Comment by ypid** [comment]
@drybjed Thanks for testing. I would like to go with Trusty if that is fine with you and drop the legacy support. I will try to make this role work on jessie related to #2 later to allow testing it.

**Comment by drybjed** [comment]
OK then, gonna try enabling Trusty packages.

**Pull request merged**
